# Configuration de base pour GitHub Pages

# Paramètres du site
title: "Recherche sur la conformité SOC - Yamify"
description: "Documentation sur la conformité SOC 2 pour Yamify sur EKS et GKE"
baseurl: "/soc-compliance"  # Chemin du dépôt
url: "https://yamify-org.github.io"  # Votre nom d'utilis/organisation GitHub

# Paramètres Jekyll
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  auto_ids: true
  math_engine: mathjax

# Thème et mise en page
theme: jekyll-theme-cayman

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-mermaid

# Configuration Mermaid
mermaid:
  version: "8.14.0"
  src: "https://cdn.jsdelivr.net/npm/mermaid@8.14.0/dist/mermaid.min.js"
  config:
    startOnLoad: true
    theme: "default"
    securityLevel: "loose"

# Valeurs par défaut
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
      toc: true
      toc_float: true
      show_sidenav: true

# Exclure les fichiers inutiles
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - .bundle/
  - .vscode/
  - .gitignore
  - .editorconfig
  - .ruby-version
  - .ruby-gemset
  - .DS_Store
  - Thumbs.db

# Paramètres d'affichage
show_downloads: true
show_toc: true

# Configuration du pied de page
footer:
  - label: "GitHub"
    icon: "github"
    url: "https://github.com/yamify-org/soc-compliance"
  - label: "Licence MIT"
    icon: "balance-scale"
    url: "/LICENSE"

# Configuration des couleurs
color_theme: "auto"  # auto, light, dark

# Configuration des métadonnées SEO
seo:
  name: "Yamify"
  links:
    - "https://github.com/yamify-org"
    - "https://twitter.com/yamify"

# Paramètres avancés
kramdown:
  math_engine: mathjax
  syntax_highlighter_op
