# Configuration for GitHub Pages
# See https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/configuration-files-for-github-pages-sites

# Site settings
title: Documentation SOC 2 pour Kubernetes
description: Documentation de recherche sur la conformité SOC de Yamify
baseurl: "" # Vide pour un dépôt de projet
url: "https://yamify-org.github.io" # URL de base de votre site

# Jekyll settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Theme settings
theme: jekyll-theme-cayman

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-relative-links

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      show_downloads: true
      show_toc: true

# Configuration for 404 page
plugins:
  - jekyll-redirect-from

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - CHANGELOG.md
  - .gitignore
  - .github/
  - .vscode/
  - _site/
  - vendor/
  - node_modules/
  - .bundle/
  - .jekyll-cache/
  - .sass-cache/
  - .DS_Store
  - Thumbs.db

# 404 page configuration
not_found_page_style: default

# Sitemap configuration
sitemap:
  exclude:
    - /404.html
    - /assets/
    - /images/
    - /js/
    - /css/
  change_frequency: weekly
  priority: 0.7

# SEO Configuration
twitter_username: yamify_org
github_username:  yamify-org

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Timezone
timezone: Europe/Paris

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      author: yamify
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      comments: false
      author: yamify

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - .gitignore
  - .github/
  - .vscode/
  - _config.yml
  - _site/
  - vendor/
  - node_modules/
  - package.json
  - package-lock.json
  - .bundle/
  - .jekyll-cache/
  - .sass-cache/
  - .DS_Store
  - Thumbs.db

# Enable support for Mermaid diagrams
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      mermaid:
        css: class
        span:
          class: false

# Plugins
plugins:
  - jekyll-mermaid
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github
  - .gitignore
  - README.md
  - LICENSE
  - .DS_Store
  - .jekyll-cache
  - .sass-cache
  - _site

# Build settings
repository: yamify-org/soc-compliance
url: https://yamify-org.github.io/soc-compliance
baseurl: /soc-compliance

# Navigation
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      show_downloads: true
      show_toc: true
      nav_order: 1

# Theme settings
theme_config:
  show_downloads: true
  show_toc: true
  search: true
  # Custom CSS
  custom_css:
    - /assets/css/style.css

# Mermaid configuration
mermaid:
  # Pick a theme (default, dark, forest, or neutral)
  theme: default
  # Set the display mode (true for full-width, false for centered)
  fullWidth: true
  # Set the scale of the diagram (1.0 = 100%)
  scale: 1.0
  # Set the background color (useful for dark themes)
  backgroundColor: transparent

# SEO settings
twitter:
  username: yamify-org

github:
  repository_url: https://github.com/yamify-org/soc2-kubernetes-docs

# Build settings
timezone: Europe/Paris
future: true
incremental: false

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

    sort_by: nav_order

# Defaults
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: docs
      toc: true
      toc_label: "Table des matières"
      toc_icon: "list"
      search: true
